_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.8.5
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 41
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.5
            "5": 0.19.10
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.10
            "13": linux-x86_64
dataset:
    value:
        data_dir: /media/e210/HD81/Adhvaith_datasets/nsclc_public
        data_file: /media/e210/HD81/Adhvaith_datasets/results/datasets/test_20/volumes_dataset.pkl
        data_pkl: /media/e210/HD81/Adhvaith_datasets/results/datasets/test_20/volumes_dataset.pkl
        input_size:
            - 64
            - 64
            - 64
        input_size_2d: 256
        n_test_samples: 20
        patch_size:
            - 64
            - 64
        patch_size_3d:
            - 16
            - 64
            - 64
        test_mode: true
        test_ratio: 0.1
        train_ratio: 0.8
        use_single_file: true
        val_ratio: 0.1
hyperparameters:
    value:
        batch_size: 4
        beta: 0.30138649046798016
        early_stopping_patience: 10
        epochs: 100
        learning_rate: 1.2902113024567147e-05
        weight_decay: 0.0005306371575220846
model:
    value:
        base_filters: 23
        bottleneck_filters: 256
        dropout_rate: 0.3
        in_channels: 1
        is_2d: false
        latent_dim: 73
        type: vae
optuna:
    value:
        direction: minimize
        n_trials: 50
        pruner: median
        sampler: tpe
        timeout: 86400
        use_optuna: false
output:
    value:
        log_dir: /media/e210/HD81/Adhvaith_datasets/results/logs
        model_dir: /media/e210/HD81/Adhvaith_datasets/results/models
        results_dir: /media/e210/HD81/Adhvaith_datasets/results
patch_extraction:
    value:
        enable: false
        max_patches_per_slice: 100
        max_patches_per_volume: 500
        patch_dimension: 3D
        patch_size:
            - 50
            - 50
            - 50
        patch_unit_type: voxels
        random_state: 42
        threshold: 0.01
preprocessing:
    value:
        batch_size: 1000
        extract_slices: false
        non_zero_threshold: 0.05
        normalize: false
        normalize_method: 95percentile
        num_workers: 8
        percentile_norm: 95
        resize_to:
            - 128
            - 128
            - 64
        slice_extraction: informative
        unit_type: voxels
        use_tanh_output: false
        voxel_spacing:
            - 2
            - 2
            - 2
training:
    value:
        accumulation_steps: 1
        gpu_id: 0
        grad_clip: 0.1
        loss: mse
        non_zero_loss: false
        optimizer: rmsprop
        scheduler: cosine_annealing
        seed: 42
transforms:
    value:
        adjust_brightness: true
        augment: true
        flip: true
        random_crop: false
        random_noise: false
        rotate: true
trial_num:
    value: 6
wandb:
    value:
        entity: pgsalome
        group: resumed_opt_20250426_231549
        name: trial_6
        project_name: dose_distribution_autoencoder
        tags:
            - optimization
            - trial_6
        use_wandb: true
